Repository sqitchers/sqitch, pull requests merged in 2019-06, with the labels that each got.

#469 Increment 1.0.1
  .travis.yml
  Changes
  dist.ini
  dist/sqitch.spec
Labels: todo

#471 Test Perl 5.30.
  .travis.yml
Labels: todo

#470 Fixed pod error as reported by CPANTS.
  lib/sqitch-checkout.pod
Labels: documentation

#474 Fix l10n-related test failures.
  Changes
  po/it_IT.po
  t/add.t
  t/base.t
  t/bundle.t
  t/checkout.t
  t/deploy.t
  t/engine.t
  t/engine_cmd.t
  t/init.t
  t/rebase.t
  t/revert.t
  t/status.t
  t/target_cmd.t
  t/verify.t
Labels: bug, localization

#476 Properly fall back on username.
  Changes
  lib/App/Sqitch.pm
Labels: bug
